services:
  - type: web
    name: shin-shop-backend
    env: node
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
