services:
  - type: web
    name: shin-shop-backend
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        value: "postgres://medusa_user:medusa_password@dpg-ctqhj8lds78s73e5qlr0-a.oregon-postgres.render.com/medusa_db"
