services:
  - type: web
    name: shin-shop-backend
    env: node
    rootDir: ./medusa-backend
    buildCommand: ./build-backend.sh
    startCommand: ./start-backend.sh
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
